### ISSUE TITLE
Create short anonymous function notation

### ISSUE THREAD

**Issue by wqferr** [wqferr/functional#13]
[This lua-users page](http://lua-users.org/wiki/ShortAnonymousFunctions) has some initial ideas. Obviously patching the Lua parser is not an option.

Currently I'm leaning towards the "Stringified Anonymous Functions" pattern.

**Comment by wqferr** [comment]
[lua-stdlib's functional module](https://lua-stdlib.github.io/functional/modules/functional.html#lambda) could also be used for inspiration.

**Comment by FractalU** [comment]
I'm personally against "Stringified Anonymous Functions" pattern, because it makes type checking impossible in teal. So what I get from lua-stdlib's functional module is that the lambda function takes a string as an argument and compiles it down to a function. So it's basically a glorified loadstring that tries to mimic a closure. The type signature of lambda has to be something like 'function(string): function(...: any): any'. The type signature of 'fn' has to be something like 'function(string, function(...: any): any): function(any: ...): any'.The point is that stringified anonymous functions destroy type information. In teal, anonymous functions are verbose due to lack of strong type inference. An example code in teal:

local f = require("functional")

local three = f.take({ 1 , 2, 3, 4, 5, 6, 7 }, 3):skip(1):to_array()
for _, v in ipairs(three) do
    print(v)
end

local a = f.iterate({ 7, 6, 5, 4, 3, 2, 1 }):reduce(function(acc: string, v: integer): string
    return acc..v
end, "")
print(a)

local arr = { 1, 2, 3, 4, 5 }
f.filter(arr, function(v: integer): boolean return v % 2 == 1 end):foreach(function(v: integer)
     print(v)
end)

I would rather have a closure syntax or better type inference supported in teal. The above code is verbose, but it's actually readable and types are easily seen. In real world code I would rather prefer annotated types, because it makes the code more readable. I find real world rust and haskell code hard to read due to the combination of overuse of closures and lack of annotated types.

The main reason why I'm against this feature is that it makes type checking impossible in teal. For me, it's more of a feature that looks appealing but doesn't really add real value.

**Comment by FractalU** [comment]
Here is the issue for better type inference in teal.
https://github.com/teal-language/tl/issues/145
Well, it looks like teal won't have this feature implemented anytime soon.

**Comment by wqferr** [comment]
Indeed, Stringified Anonymous Functions would be quite annoying to deal with in Teal, everything you said is true. I'm currently working on those in the branch `lambdas` if you want to have a look, and I will create a proper PR shortly.

My current thought process is that, while I want Teal to become commonplace, it's still not quite there yet. This is primarily a Lua library with partial Teal support. Lambdas are something most functional-style libraries include some way or another, and it's one of the core features missing from this one.

That is not to say I think the .d.tl should exclude lambdas entirely: in one of the test scripts I added to the repo in that branch, I have as a proof of concept:

```lua
local f = require "functional"

print(f.range(3, 37, 4):reduce(f.lambda "b - a", 0))
f.range(10)
  :map(f.lambda "2*x" as f.mapping<integer, integer>)
  :foreach(print as f.consumer<integer>)
```

Using explicit function types such as `mapping` and `consumer` is far from ideal, but I believe it works well enough to be usable.
